version: '2'
services:
  dev:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./source:/usr/src/app/source
  build:
    extends: dev
    command: build
    volumes:
      - ./build:/usr/src/app/build
